"""
Seeds PSU's General Education requirements into the requirements table
under the reserved program_name "__GEN_ED__".

These are university-wide graduation requirements, not major-specific.
Uses pool-based (choose_credits / choose_courses) groups for attribute
categories and required-exact rows for the two mandatory first-year courses.

Interdomain / dual-designated courses
--------------------------------------
Some PSU courses carry TWO gen ed attribute codes (e.g. "GH; US" or "GN; GS").
These are listed in BOTH of their respective pools and flagged multi_category=True.
The audit engine exempts multi_category courses from the consumed set, so a single
course can satisfy two categories simultaneously — which is exactly what PSU allows.

Course code format
------------------
All gen ed designation suffixes (W, N, Q, Y, S, H) are STRIPPED from course codes
because the transcript parser also strips those suffixes.  Only the base code is
stored so that audit matching works correctly (e.g. "IST 302W" → "IST 302").

Usage:
    python scripts/seed_gen_ed.py

Safe to re-run — uses PutItem upserts.
"""

import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from decimal import Decimal
from dotenv import load_dotenv
load_dotenv()

from db import requirements_table

PROGRAM = "__GEN_ED__"

# ── Gen Ed requirement definitions ──────────────────────────────────────────
# Tuple fields:
#   (requirement_group, group_type, group_threshold,
#    course_code, course_title, credits, min_grade,
#    pair_group_id, multi_category)
#
# multi_category=True  → course carries 2 PSU gen ed attributes.
#                         It is listed in both pools and exempt from the
#                         course-consumption rule (satisfies both groups).
# multi_category=False → normal single-category course (most rows).
#
# group_threshold: for choose_credits = minimum credits required
#                  for choose_courses = minimum number of courses required
#                  None for choose_one groups

GEN_ED_ROWS = [

    # ════════════════════════════════════════════════════════════════════════
    # COMMUNICATION: EFFECTIVE SPEECH (choose one section)
    # ════════════════════════════════════════════════════════════════════════
    # multi_category=True so these are NOT consumed after satisfying Effective
    # Speech — PSU allows them to also satisfy GH: Humanities simultaneously.
    ("Communication: Effective Speech", "choose_one", None,
     "CAS 100A", "Effective Speech", 3, "D", 1, True),
    ("Communication: Effective Speech", "choose_one", None,
     "CAS 100B", "Effective Speech", 3, "D", 1, True),
    ("Communication: Effective Speech", "choose_one", None,
     "CAS 100C", "Effective Speech", 3, "D", 1, True),

    # ════════════════════════════════════════════════════════════════════════
    # COMMUNICATION: WRITING (ENGL 15 or ENGL 30H)
    # ════════════════════════════════════════════════════════════════════════
    ("Communication: Writing", "choose_one", None,
     "ENGL 15",  "Rhetoric and Composition", 3, "D", 2, False),
    ("Communication: Writing", "choose_one", None,
     "ENGL 30",  "Honors Rhetoric and Composition", 3, "D", 2, False),

    # ════════════════════════════════════════════════════════════════════════
    # GQ — QUANTIFICATION (6 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 4",   "College Algebra", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 17",  "Mathematical Concepts", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 18",  "Elementary Linear Algebra", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 21",  "College Algebra I", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 22",  "College Algebra II", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 26",  "Plane Trigonometry", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 41",  "Trigonometry and Analytic Geometry", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 83",  "Mathematics for Sustainability", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 110", "Techniques of Calculus I", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 111", "Techniques of Calculus II", 2, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 140", "Calculus with Analytic Geometry I", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 141", "Calculus with Analytic Geometry II", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 200", "Mathematics for Business", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 220", "Matrices", 2, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 230", "Calculus and Vector Analysis", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 231", "Calculus of Several Variables", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 250", "Ordinary Differential Equations", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 251", "Ordinary and Partial Differential Equations", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 311", "Concepts of Discrete Mathematics", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "MATH 312", "Concepts of Real Analysis", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 100", "Statistical Concepts and Reasoning", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 200", "Elementary Statistics", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 250", "Introduction to Biostatistics", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 301", "Statistics for Data Science", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 318", "Statistics for Social Sciences", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 415", "Introduction to Mathematical Statistics I", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "STAT 416", "Introduction to Mathematical Statistics II", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "CMPSC 121","Introduction to Programming Techniques", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "CMPSC 131","Programming and Computation I", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "IST 210",  "Organization of Data", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "DS 200",   "Introduction to Data Sciences", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "ACCTG 211","Financial and Managerial Accounting for Decision Making", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "ECON 306", "Statistics for Economics and Business", 3, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "PSYCH 200","Quantitative Methods in Psychology", 4, "D", None, False),
    ("GQ: Quantification", "choose_credits", 6,
     "SOC 283",  "Sociological Statistics", 3, "D", None, False),

    # ════════════════════════════════════════════════════════════════════════
    # GN — NATURAL SCIENCES (6 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    ("GN: Natural Sciences", "choose_credits", 6,
     "ASTRO 1",  "Astronomical Universe", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "ASTRO 2",  "The Solar System", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "ASTRO 10", "Introduction to Astronomy", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "ASTRO 11", "Astronomical Universe — Honors", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 4",   "Understanding Biosystems", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 11",  "Biology: The Study of Life", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 13",  "Plants and Human Affairs", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 110", "Basic Concepts in Biology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 127", "Biology of Nutrition", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 129", "Biology of Sex and Reproduction", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 133", "Biology of Social Behavior", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 141", "Foundations of Biology: Biological Diversity, Ecology, and Evolution", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 142", "Foundations of Biology: Molecular and Cellular Biology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 155", "Human Biology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 220", "Genetics", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 230", "Cell and Developmental Biology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "BIOL 240", "Microbiology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 4",   "Introductory Chemistry", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 12",  "Survey of Chemistry", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 13",  "Survey of Chemistry Laboratory", 1, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 100", "Chemistry in Society", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 101", "Introductory Chemical Science", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 110", "Chemical Principles I", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 111", "Chemical Principles Laboratory I", 1, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 112", "Chemical Principles II", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "CHEM 113", "Chemical Principles Laboratory II", 1, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EARTH 2",  "Earth History", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EARTH 6",  "Environmental Geology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EARTH 10", "Geology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EARTH 100","Earth and Environment", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EARTH 101","Earth and Space", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "ERTH 10",  "Geology", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 10",  "Physical Geography", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 20",  "Weather and Climate", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 120", "Environment and Society", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 121", "Global Climate Change", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "METEO 3",  "Weather", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "METEO 101","Weather and Climate", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 1",   "The Science of Sound", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 2",   "Light and Color", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 3",   "The Physics of Music", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 10",  "Physics for Citizens", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 100", "Introductory Physics", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 211", "General Physics: Mechanics", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 212", "General Physics: Electricity and Magnetism", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 213", "General Physics: Modern Physics", 2, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 214", "General Physics: Waves, Electricity, Magnetism", 2, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 250", "Introductory Physics I", 4, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 251", "Introductory Physics II", 4, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "PHYS 260", "General Physics: Mechanics and Relativity", 4, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "NUCE 100", "Introduction to Nuclear Science and Engineering", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "ENSC 100", "Introduction to Environmental Sciences", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "EE 210",   "Electrical Engineering Fundamentals I", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "MATSE 100","Materials in Today's World", 3, "D", None, False),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOSC 40", "Geology of National Parks", 3, "D", None, False),
    # Interdomain GN;GS
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 1",   "Human Geography", 3, "D", None, True),
    ("GN: Natural Sciences", "choose_credits", 6,
     "GEOG 40",  "Environmental Geography", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # GA — ARTS (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    ("GA: Arts", "choose_credits", 3,
     "ART 1",    "Art Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 2",    "History of Western Art I", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 3",    "History of Western Art II", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 10",   "Introduction to Studio Art", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 100",  "Art Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 101",  "Introductory Drawing", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 102",  "Introductory Painting", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 103",  "Introductory Ceramics", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 104",  "Introductory Photography", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 105",  "Introductory Printmaking", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 106",  "Introductory Sculpture", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 201",  "Two-Dimensional Design", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 202",  "Three-Dimensional Design", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 210",  "History of Modern Art", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ART 211",  "History of Contemporary Art", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DART 10",  "Introduction to Digital Arts", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DART 100", "Digital Arts", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DART 200", "Digital Video Art", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DANC 1",   "Introduction to Dance", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DANC 47",  "Dance Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "DANC 100", "Introduction to Dance Studies", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "FILM 10",  "Introduction to Film", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "FILM 100", "Introduction to Film", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "FILM 101", "Film Genres", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 1",   "The Enjoyment of Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 2",   "Introduction to World Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 7",   "Understanding Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 8",   "Rock Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 9",   "Jazz Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 10",  "Introduction to Music Technology", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 100", "Music Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 101", "Introduction to World Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 106", "History of Rock", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "THEA 1",   "Introduction to Theatre", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "THEA 10",  "Theatre Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "THEA 100", "Introduction to Theatre", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "THEA 101", "Theatre Appreciation", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "THEA 200", "Theatre and Drama", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "MUSIC 11", "Introduction to Music", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "PHOT 100", "Introduction to Photography", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "COMM 100", "Survey of Communications", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ARCH 100", "Introduction to Architecture", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ARCH 111", "Design I", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "LA 1",     "Introduction to Landscape Architecture", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ENGL 4",   "Introduction to Creative Writing", 3, "D", None, False),
    ("GA: Arts", "choose_credits", 3,
     "ENGL 5",   "Introduction to Poetry", 3, "D", None, False),
    # Interdomain GA;GH
    ("GA: Arts", "choose_credits", 3,
     "ENGL 202A","Creative Writing: Fiction", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "ENGL 202B","Creative Writing: Poetry", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "ENGL 202E","Creative Nonfiction Writing", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "CAS 138",  "Argument and Civic Life", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "THEA 210", "History of Western Theatre I", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "THEA 211", "History of Western Theatre II", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 108", "History of Western Music I", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "MUSC 109", "History of Western Music II", 3, "D", None, True),
    ("GA: Arts", "choose_credits", 3,
     "ART 204",  "Survey of Asian Art", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # GH — HUMANITIES (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    ("GH: Humanities", "choose_credits", 3,
     "HIST 4",   "History of Ancient Greece and Rome", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 5",   "Medieval and Early Modern Europe", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 11",  "The World Since 1945", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 20",  "History of Western Civilization I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 21",  "History of Western Civilization II", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 100", "Introduction to Historical Studies", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 301", "History of Science", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 1",   "Reasoning and Critical Thinking", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 2",   "Introduction to Ethics", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 3",   "Knowledge and Reality", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 10",  "Introduction to Philosophy", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 12",  "Critical Thinking", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 100", "Morality and Justice", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PHIL 105", "Technology and Human Values", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 4",   "Introduction to Creative Writing", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 30",  "Honors Rhetoric and Composition", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 50",  "Introduction to Literature", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 111", "Literature and Writing", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 118", "Literature and Popular Culture", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 170", "Introduction to World Literature", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 200", "Survey of English Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 201", "Survey of English Literature II", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 202D","Technical Writing", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 202F","Business Writing", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 203", "Shakespeare I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 204", "Shakespeare II", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 240", "Introduction to American Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 241", "Introduction to American Literature II", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 1",   "Introduction to Religious Studies", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 2",   "World Religions I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 3",   "World Religions II", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 100", "Introduction to Religion", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAMS 45",  "Ancient Sport and Society", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAMS 100", "Introduction to Classical Studies", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAMS 108", "Classical Mythology", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CMLIT 100","Introduction to Comparative Literature", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CMLIT 110","Literature and Society", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAS 100A", "Effective Speech", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAS 100B", "Effective Speech", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAS 100C", "Effective Speech", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "CAS 252",  "Argument, Evidence, and Controversy", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "SPAN 100", "Survey of Hispanic Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "FR 100",   "Survey of French Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "GER 100",  "Survey of German Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "ITAL 100", "Introduction to Italian Literature", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "PORT 100", "Survey of Portuguese Literature I", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "LLED 100", "Language and Linguistics", 3, "D", None, False),
    ("GH: Humanities", "choose_credits", 3,
     "LING 100", "Introduction to Linguistics", 3, "D", None, False),
    # Interdomain GH;US
    ("GH: Humanities", "choose_credits", 3,
     "HIST 110", "American Civilization", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 111", "American Civilization to 1877", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 112", "American Civilization since 1877", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 240", "Introduction to American Literature I", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 241", "Introduction to American Literature II", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "AMST 100", "Introduction to American Studies", 3, "D", None, True),
    # Interdomain GH;IL
    ("GH: Humanities", "choose_credits", 3,
     "ANTH 1",   "Introduction to Anthropology", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "ANTH 21",  "Cultural Anthropology", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 10",  "Introduction to Global History", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 12",  "History of East Asia", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 13",  "History of the Middle East", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 14",  "African History", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "HIST 15",  "Latin American History", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "CMLIT 120","World Literature Survey I", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "CMLIT 121","World Literature Survey II", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 2",   "World Religions I", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "RELI 3",   "World Religions II", 3, "D", None, True),
    # Interdomain GA;GH
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 202A","Creative Writing: Fiction", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 202B","Creative Writing: Poetry", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "ENGL 202E","Creative Nonfiction Writing", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "THEA 210", "History of Western Theatre I", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "THEA 211", "History of Western Theatre II", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "MUSC 108", "History of Western Music I", 3, "D", None, True),
    ("GH: Humanities", "choose_credits", 3,
     "MUSC 109", "History of Western Music II", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # GS — SOCIAL AND BEHAVIORAL SCIENCES (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ANTH 1",   "Introduction to Anthropology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ANTH 21",  "Cultural Anthropology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ANTH 45",  "Introduction to Biological Anthropology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "COMM 150", "Introduction to Communication Theory", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "COMM 160", "Introduction to Public Communication", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "CRIMJ 100","Introduction to Criminal Justice", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "CRIMJ 200","Criminology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 1",   "Economic Way of Thinking", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 2",   "Introduction to Economic Analysis", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 14",  "Principles of Economics", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 102", "Introductory Microeconomic Analysis", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 104", "Introductory Macroeconomic Analysis", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ECON 200", "Consumer and Market Behavior", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 1",   "Human Geography", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 30",  "Human-Environment Interaction", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 100", "Introduction to Human Geography", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 1",   "American Politics", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 3",   "Introduction to Political Science", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 14",  "Introduction to Comparative Politics", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 15",  "Introduction to International Relations", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PSYCH 1",  "General Psychology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PSYCH 100","Introductory Psychology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PSYCH 110","Introduction to Social Psychology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PSYCH 200","Developmental Psychology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 1",    "Introductory Sociology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 5",    "Social Problems", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 100",  "Introductory Sociology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 119",  "Social Dimensions of Information and Communication Technology", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 148",  "Race and Ethnic Relations", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 244",  "Technology and Society", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ADTED 140","Psychology of Adult Learning", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "HD FS 129","Child Development", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "HDFS 129", "Child Development", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "HDFS 229", "Adolescent Development", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "MGMT 310", "Foundations of Management", 3, "D", None, False),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "MKTG 301", "Marketing Management", 3, "D", None, False),
    # Interdomain GS;US
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 1",   "American Politics", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 1",    "Introductory Sociology", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "CRIMJ 100","Introduction to Criminal Justice", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "AFAM 100", "Introduction to African American Studies", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "WMST 100", "Introduction to Women's Studies", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "SOC 119",  "Social Dimensions of Information and Communication Technology", 3, "D", None, True),
    # Interdomain GS;IL
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ANTH 140", "Peoples of the World", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 128", "World Regional Geography", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 40",  "Environmental Geography", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "PLSC 15",  "Introduction to International Relations", 3, "D", None, True),
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "ANTH 21",  "Cultural Anthropology", 3, "D", None, True),
    # Interdomain GN;GS
    ("GS: Social and Behavioral Sciences", "choose_credits", 3,
     "GEOG 1",   "Human Geography", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # GHW — HEALTH AND PHYSICAL ACTIVITY (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    # Lecture / concept courses (3 credits each)
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "HPA 100",  "Personal Health and Wellness", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "HM 208",   "Social, Cultural, and Health Influences of Alcohol", 1.5, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 1",  "Introduction to Kinesiology", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 7",  "Personal Health", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 10", "First Aid/Emergency Care", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 13", "Safety Education", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 100","Health and Physical Activity", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 101","Health and Fitness for Life", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "NURS 200", "Health and Wellness", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "NUTR 100", "Introductory Nutrition", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "NUTR 150", "Nutrition Today", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "NUTR 251", "Introductory Nutrition", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "BIOL 127", "Biology of Nutrition", 3, "D", None, False),
    # Activity courses (typically 1–2 credits each; 3 credits satisfies pool threshold)
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 3",  "Physical Fitness and Wellness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 4",  "Introduction to Physical Activity and Health", 2, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 11", "Downhill Skiing", 1.5, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 20", "Aerobic Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 21", "Step Aerobics", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 22", "Beginning Swimming", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 23", "Intermediate Swimming", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 24", "Advanced Swimming", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 25", "Beginning Tennis", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 26", "Intermediate Tennis", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 27", "Advanced Tennis", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 28", "Beginning Golf", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 29", "Intermediate Golf", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 30", "Advanced Golf", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 31", "Aerobics", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 32", "Fitness Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 33", "Strength and Conditioning", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 34", "Basketball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 35", "Flag Football", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 36", "Volleyball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 37", "Intermediate Volleyball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 38", "Softball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 39", "Soccer", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 40", "Racquetball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 41", "Intermediate Racquetball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 42", "Squash", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 43", "Handball", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 44", "Badminton", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 45", "Table Tennis", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 46", "Bowling", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 47", "Archery", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 48", "Fencing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 50", "Gymnastics", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 51", "Tumbling and Acrobatics", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 52", "Trampoline", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 53", "Ice Skating", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 54", "Skiing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 55", "Intermediate Skiing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 56", "Snowboarding", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 57", "Rock Climbing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 58", "Outdoor Adventures", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 59", "Kayaking", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 60", "Canoeing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 61", "Sailing", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 62", "Scuba Diving", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 63", "Cycling", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 64", "Running and Jogging", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 65", "Walking for Fitness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 66", "Hiking", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 67", "Backpacking", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 70", "Karate", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 71", "Judo", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 72", "Self Defense", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 73", "Tai Chi", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 75", "Weight Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 76", "Advanced Weight Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 77", "Olympic Weightlifting", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 78", "Powerlifting", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 80", "Yoga", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 81", "Pilates", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 82", "Meditation and Relaxation", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 83", "Stress Management", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 84", "Social Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 85", "Ballet", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 86", "Modern Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 87", "Hip Hop Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 88", "Cross-Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 89", "Conditioning for Sport", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 90", "General Fitness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 91", "Personal Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 92", "Aquatic Fitness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 93", "Sport Conditioning", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 94", "Core Training", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 95", "Functional Fitness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 96", "Indoor Cycling", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 97", "Boot Camp", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 98", "Recreational Sports", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "KINES 99", "Special Topics in Physical Activity", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "PE 1",     "Physical Education Activity", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "PE 3",     "Physical Fitness", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "DANC 1",   "Introduction to Dance", 3, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "DANC 10",  "Ballet", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "DANC 11",  "Modern Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "DANC 12",  "Jazz Dance", 1, "D", None, False),
    ("GHW: Health and Physical Activity", "choose_credits", 3,
     "DANC 13",  "Tap Dance", 1, "D", None, False),

    # ════════════════════════════════════════════════════════════════════════
    # US — UNITED STATES CULTURES (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    # Pure US (not dual-designated)
    ("US: United States Cultures", "choose_credits", 3,
     "AFAM 100", "Introduction to African American Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "AFAM 101", "African American History to 1863", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "AFAM 102", "African American History since 1863", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "AFAM 200", "Introduction to African American Literature", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "AMST 100", "Introduction to American Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "WMNST 100","Introduction to Women's Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "WMNST 200","Perspectives on Women", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "WMST 100", "Introduction to Women's Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "LGBTQ 100","Introduction to LGBTQ Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "LABOR 100","Introduction to Labor Studies", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 116", "History of Pennsylvania", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 120", "American History: Colonial to 1800", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 121", "American History: 1800 to Civil War", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 122", "American History: Civil War to 1917", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 123", "American History: 1917 to Present", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 140", "Introduction to African American History", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 162", "History of American Women", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 165", "Native American History", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "PLSC 2",   "State and Local Government", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "PLSC 10",  "Introduction to United States Government", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "COMM 170", "Media, Culture, and Society", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "COMM 200", "Media in Society", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "ENGL 240", "Introduction to American Literature I", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "ENGL 241", "Introduction to American Literature II", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "SOC 160",  "Social Inequalities", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "SOC 212",  "Introduction to Race and Ethnicity", 3, "D", None, False),
    ("US: United States Cultures", "choose_credits", 3,
     "SOC 248",  "Work and Society", 3, "D", None, False),
    # Interdomain GH;US (also listed above in GH)
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 110", "American Civilization", 3, "D", None, True),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 111", "American Civilization to 1877", 3, "D", None, True),
    ("US: United States Cultures", "choose_credits", 3,
     "HIST 112", "American Civilization since 1877", 3, "D", None, True),
    # Interdomain GS;US
    ("US: United States Cultures", "choose_credits", 3,
     "PLSC 1",   "American Politics", 3, "D", None, True),
    ("US: United States Cultures", "choose_credits", 3,
     "SOC 1",    "Introductory Sociology", 3, "D", None, True),
    ("US: United States Cultures", "choose_credits", 3,
     "CRIMJ 100","Introduction to Criminal Justice", 3, "D", None, True),
    ("US: United States Cultures", "choose_credits", 3,
     "SOC 119",  "Social Dimensions of Information and Communication Technology", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # IL — INTERNATIONAL CULTURES (3 credits minimum)
    # ════════════════════════════════════════════════════════════════════════
    # Pure IL (single-category)
    ("IL: International Cultures", "choose_credits", 3,
     "SPAN 1",   "Elementary Spanish I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "SPAN 2",   "Elementary Spanish II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "SPAN 3",   "Intermediate Spanish", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "SPAN 4",   "Intermediate Spanish II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "FR 1",     "Elementary French I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "FR 2",     "Elementary French II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "FR 3",     "Intermediate French", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "GER 1",    "Elementary German I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "GER 2",    "Elementary German II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "GER 3",    "Intermediate German", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "ITAL 1",   "Elementary Italian I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "ITAL 2",   "Elementary Italian II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "PORT 1",   "Elementary Portuguese I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "PORT 2",   "Elementary Portuguese II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "CHIN 1",   "Elementary Chinese I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "CHIN 2",   "Elementary Chinese II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "JAPNS 1",  "Elementary Japanese I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "JAPNS 2",  "Elementary Japanese II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "ARAB 1",   "Elementary Arabic I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "ARAB 2",   "Elementary Arabic II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "RUSS 1",   "Elementary Russian I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "RUSS 2",   "Elementary Russian II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "HEBR 1",   "Elementary Hebrew I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "HEBR 2",   "Elementary Hebrew II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "GREK 1",   "Elementary Ancient Greek I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "LAT 1",    "Elementary Latin I", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "LAT 2",    "Elementary Latin II", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "INTL 100", "Introduction to International Affairs", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "GEOG 128", "World Regional Geography", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "PLSC 15",  "Introduction to International Relations", 3, "D", None, False),
    ("IL: International Cultures", "choose_credits", 3,
     "PLSC 14",  "Introduction to Comparative Politics", 3, "D", None, False),
    # Interdomain GH;IL
    ("IL: International Cultures", "choose_credits", 3,
     "ANTH 1",   "Introduction to Anthropology", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "ANTH 21",  "Cultural Anthropology", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 10",  "Introduction to Global History", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 12",  "History of East Asia", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 13",  "History of the Middle East", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 14",  "African History", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 15",  "Latin American History", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "CMLIT 120","World Literature Survey I", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "CMLIT 121","World Literature Survey II", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "RELI 2",   "World Religions I", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "RELI 3",   "World Religions II", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "RELI 1",   "Introduction to Religious Studies", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 20",  "History of Western Civilization I", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "HIST 21",  "History of Western Civilization II", 3, "D", None, True),
    # Interdomain GS;IL
    ("IL: International Cultures", "choose_credits", 3,
     "ANTH 140", "Peoples of the World", 3, "D", None, True),
    ("IL: International Cultures", "choose_credits", 3,
     "GEOG 40",  "Environmental Geography", 3, "D", None, True),

    # ════════════════════════════════════════════════════════════════════════
    # GWS — WRITING ACROSS THE CURRICULUM (3 W-designated courses minimum)
    # Note: transcript parser strips the W suffix, so "IST 302W" → "IST 302"
    # The audit engine matches the stripped code against what is listed here.
    # GWS requires 3 courses; choose_courses threshold = 3.
    # ════════════════════════════════════════════════════════════════════════

    # ── IST / SRA / DS ──────────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "IST 302",  "Information and Organizations", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "IST 331",  "Information and Persuasion", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "IST 356",  "Contemporary Issues in IST", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "IST 432",  "Strategic Leadership of Technology", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "IST 440",  "IST Integration and Problem Solving", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "SRA 111",  "Security Risk Analysis", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "SRA 321",  "Security Risk Assessment", 3, "D", None, False),

    # ── ENGL ────────────────────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202A","Creative Writing: Fiction", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202B","Creative Writing: Poetry", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202C","Professional Writing", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202D","Technical Writing", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202E","Creative Nonfiction Writing", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202F","Business Writing", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202G","Writing about Literature", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 202H","Writing for Honors", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 413", "Advanced Writing: Fiction", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 416", "Advanced Writing: Nonfiction", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGL 418", "Advanced Writing: Poetry", 3, "D", None, False),

    # ── CAS / COMM ──────────────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CAS 138",  "Argument and Civic Life", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CAS 252",  "Argument, Evidence, and Controversy", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "COMM 200", "Media in Society", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "COMM 260", "Research Methods in Communication", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "COMM 320", "Communication Law", 3, "D", None, False),

    # ── BIOL / CHEM / EARTH / PHYS ──────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "BIOL 230", "Cell and Developmental Biology", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "BIOL 427", "Physiology", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CHEM 210", "Organic Chemistry I", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CHEM 212", "Organic Chemistry II", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "EARTH 402","Geology and the Environment", 3, "D", None, False),

    # ── HIST / PLSC / SOC / PSYCH / ECON ────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HIST 416", "Topics in American History", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HIST 421", "History Capstone", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "PLSC 308", "Constitutional Law", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "SOC 430",  "Sociological Theory", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "PSYCH 313","Research Methods in Psychology", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ECON 301", "Intermediate Microeconomics", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ECON 302", "Intermediate Macroeconomics", 3, "D", None, False),

    # ── MGMT / MKTG / FIN / ACCTG / BA ─────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MGMT 301", "Organizational Behavior", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MGMT 310", "Foundations of Management", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MGMT 404", "Strategic Management", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MKTG 305", "Marketing Research", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "FIN 301",  "Corporate Finance", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "BA 300",   "Business Communication", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "BA 301",   "Corporate Finance", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "BLAW 442", "Advanced Business Law", 3, "D", None, False),

    # ── ETI / CYBER / SCM / HPA ─────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ETI 461",  "Technology Leadership", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ETI 471",  "ETI Capstone I", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CYBER 100","Introduction to Cybersecurity", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "SCM 301",  "Supply Chain Management", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HPA 291",  "Epidemiology and Health Statistics", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HPA 309",  "Health Care Policy", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "NUTR 400", "Nutrition through the Life Cycle", 3, "D", None, False),

    # ── KINES / NURS / HD FS / EDPSY ────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "KINES 360","Exercise Physiology", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "KINES 451","Motor Learning", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "NURS 300", "Nursing Research", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HDFS 445", "Human Sexuality", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "EDPSY 014","Human Development and Learning", 3, "D", None, False),

    # ── ANTH / GEOG / SOCY / AFAM / WMST ────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ANTH 440", "Anthropological Theory", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "GEOG 302", "Global Environmental Change", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "AFAM 410", "African American Social Thought", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "WMST 300", "Feminist Theory", 3, "D", None, False),

    # ── PHIL / RELI / CAMS ──────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "PHIL 407", "Advanced Logic", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "PHIL 410", "Ethics and Society", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "RELI 404", "Religion and Culture", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CAMS 403", "Classical Texts in Translation", 3, "D", None, False),

    # ── ART / MUSC / THEA ───────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ART 431",  "Contemporary Art Theory", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MUSC 400", "Music History Seminar", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "THEA 401", "Theatre Research and Writing", 3, "D", None, False),

    # ── ARCH / LA / ENGR ────────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ARCH 400", "Architecture Theory", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "LA 403",   "Landscape Architecture Studio", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ENGR 340", "Engineering Communications", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CE 400",   "Civil Engineering Professional Issues", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "EE 402",   "Electrical Engineering Capstone", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "ME 408",   "Engineering Design and Professionalism", 3, "D", None, False),

    # ── FRNSC / CRIM / LAW ──────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "FRNSC 405","Forensic Science Capstone", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "FRNSC 415","Advanced Forensic Science Topics", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CRIMJ 400","Criminological Theory", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CRIMJ 480","Senior Seminar in Criminal Justice", 3, "D", None, False),

    # ── CMPSC / MATH / STAT ─────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CMPSC 431","Database Management Systems", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "CMPSC 465","Data Structures and Algorithms", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "MATH 401", "Mathematical Analysis I", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "STAT 460", "Experimental Design", 3, "D", None, False),

    # ── AGRI / FOOD SCI / HM ────────────────────────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "AGBM 352", "Agricultural Economics", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "FSC 400",  "Food Science Capstone", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HM 301",   "Hospitality Services Management", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "RHS 350",  "Rehabilitation and Human Services", 3, "D", None, False),

    # ── General upper-division writing seminars ──────────────────────────────
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "HCDD 410", "Advanced Topics in Human-Centered Design", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "INART 400","Interdisciplinary Arts Seminar", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "INTST 400","International Studies Seminar", 3, "D", None, False),
    ("GWS: Writing Across the Curriculum", "choose_courses", 3,
     "LBST 400", "Liberal Arts Capstone", 3, "D", None, False),

]


def seed_gen_ed():
    print(f"Seeding gen ed requirements under program_name='{PROGRAM}'...")
    count = 0
    with requirements_table.batch_writer() as batch:
        for i, row in enumerate(GEN_ED_ROWS):
            (group, gtype, threshold, code, title, credits,
             min_grade, pair_id, multi_cat) = row

            group_course = f"{group}#{code}#{i}"

            item = {
                "program_name":      PROGRAM,
                "group_course":      group_course,
                "requirement_group": group,
                "group_type":        gtype,
                "course_code":       code,
                "course_title":      title,
                "credits":           Decimal(str(credits)),
                "min_grade":         min_grade,
            }

            if threshold is not None:
                item["group_threshold"] = Decimal(str(threshold))

            if pair_id is not None:
                item["pair_group_id"] = Decimal(str(pair_id))

            if multi_cat:
                item["multi_category"] = True

            batch.put_item(Item=item)
            count += 1

    print(f"  {count} gen ed rows written.")
    multi = sum(1 for r in GEN_ED_ROWS if r[8])
    print(f"  {multi} rows flagged multi_category (interdomain / dual-designated).")


if __name__ == "__main__":
    seed_gen_ed()
    print("\nGen Ed seeding complete.")
